### ISSUE TITLE
[Icon request] Flatpak Apps

### ISSUE THREAD

**Issue by hhawkens** [TaylanTatli/Sevi#1]
(Fedora 36, Gnome 42, libadwaita)

Some in-app icons seem to be missing (all flatpak):
- [x] Start page of **Mousai**
- [x] Start page of **Fragments** (small icon)

Icons for apps (all flatpak) :
- [x] PCSX2
- [x] PCSX2 Qt (comes bundled with the regular version, I guess)
- [x] RPCS3
- [x] Xemu
- [x] Heroic Games Launcher
- [x] Dolphin Emulator
- [x] Retroarch
- [x] Youp for WhatsApp
- [x] Brave
- [x] Parsec
- [x] JDownloader
- [x] Junction
- [x] Mousai
- [x] Shortwave
- [x] Jellyfin Media Player
- [x] Gnome Subtitles
- [x] Mkv Toolnix GUI
- [x] Duolingo
- [x] Godot Engine
- [x] Freetube
- [x] Nextcloud Desktop
- [x] Filezilla
- [x] Authenticator (Gnome app)
- [x] PDF Arranger
- [x] Paper
- [x] Bottles

PS: Great icon theme overall!

**Comment by TaylanTatli** [comment]
Hi! Thank you. I never used flatpak, is it use the same icon names as non flatpak version? Can you share the name of the icons, so I can start working on them?

**Comment by baduhai** [comment]
Unfortunately, flatpaks don't always have the same icon name as non-flatpaked icons. The flatpak for mpv uses `io.mpv.Mpv` icon name, for example. The way I've seen other icon packs manage this, is by symlinking to the original icon name with the flatpak icon name.

**Comment by hhawkens** [comment]
> Hi! Thank you. I never used flatpak, is it use the same icon names as non flatpak version? Can you share the name of the icons, so I can start working on them?

I am not sure what the names of these icons are. How can I find out?

**Comment by TaylanTatli** [comment]
> > Hi! Thank you. I never used flatpak, is it use the same icon names as non flatpak version? Can you share the name of the icons, so I can start working on them?
> 
> I am not sure what the names of these icons are. How can I find out?

I will look into it.

**Comment by TaylanTatli** [comment]
> Some in-app icons seem to be missing (all flatpak):
>     * Start page of **Mousai**
>     * Start page of **Fragments** (small icon)

Can you share screenshot for theese? I installed apps from flatpak and didn't see any problem. Also updated app icons for theese.

**Comment by hhawkens** [comment]
> > Some in-app icons seem to be missing (all flatpak):
> > * Start page of **Mousai**
> > * Start page of **Fragments** (small icon)
> 
> Can you share screenshot for theese? I installed apps from flatpak and didn't see any problem. Also updated app icons for theese.

Sure:

![fragments](https://user-images.githubusercontent.com/16738623/185005341-0a94f13e-8b54-409d-88fb-f4f951b2cb99.png)
![mousai](https://user-images.githubusercontent.com/16738623/185005368-b0f736b9-ae81-4cdb-8237-b63eb9c26d0a.png)

**Comment by TaylanTatli** [comment]
![Ekran Görüntüsü - 2022-08-17 17-00-18](https://user-images.githubusercontent.com/754514/185153578-fe03e57e-fcd4-415a-878d-6f70227ab73f.png)


@hhawkens This is weird. This theme inherits **Adwaita on Gnome** and **Breeze on KDE**. Do you use any of them? I didn't add all the action icons. Also if you use `Sevi-Dark`, do you have also `Sevi`?

BTW I added icon for Mousai, it should be ok now.

**Comment by TaylanTatli** [comment]
Hey @hhawkens, I added all the icons you want. Only Fragments' action icons are left.

**Comment by hhawkens** [comment]
> ![Ekran Görüntüsü - 2022-08-17 17-00-18](https://user-images.githubusercontent.com/754514/185153578-fe03e57e-fcd4-415a-878d-6f70227ab73f.png)
> 
> @hhawkens This is weird. This theme inherits **Adwaita on Gnome** and **Breeze on KDE**. Do you use any of them? I didn't add all the action icons. Also if you use `Sevi-Dark`, do you have also `Sevi`?
> 
> BTW I added icon for Mousai, it should be ok now.

I use Adwaita dark (shell theme) and I have Sevi and Sevi-dark installed. No idea whats wrong there, but it has to do with the icon theme (not just Sevi, others like Win11-dark do not work either). When I switch to the Adwaita icon theme, it shows the correct icon.

**Comment by TaylanTatli** [comment]
> I use Adwaita dark (shell theme) and I have Sevi and Sevi-dark installed. No idea whats wrong there, but it has to do with the icon theme (not just Sevi, others like Win11-dark do not work either). When I switch to the Adwaita icon theme, it shows the correct icon.

Sorry I can't help with this, Flatpak version works as expected on me. Maybe there is something wrong in your configs?
