### ISSUE TITLE
[Icon request] tidal-hifi // tidal

### ISSUE THREAD

**Issue by theJuanon** [TaylanTatli/Sevi#14]
- **App Name: tidal-hifi // tidal**
- **Icon Name: tidal-hifi // tidal**
- **Description: A streaming service for all music fans.**
- **Webpage (optional): https://github.com/Mastermindzh/tidal-hifi/ // https://tidal.com/**
- **Original Icon:**
    
![icon](https://user-images.githubusercontent.com/56099545/214372970-ba55dec5-6055-462e-b8d1-e70b12d60d29.png)

**Comment by TaylanTatli** [comment]
Thanks. Done.
